### ISSUE TITLE
code duplication

### ISSUE THREAD

**Issue by attilaz** [GameTechDev/ASSAO#11]
Some member variables are set to NULL twice.

https://github.com/GameTechDev/ASSAO/blob/master/Projects/ASSAO/ASSAO/ASSAODX11.cpp#L493
https://github.com/GameTechDev/ASSAO/blob/master/Projects/ASSAO/ASSAO/ASSAODX11.cpp#L498

**Comment by fstrugar** [comment]
Fixed (can't believe it took me this long to remember to do it, sorry) :)
