### ISSUE TITLE
Comparison with other SSAO?

### ISSUE THREAD

**Issue by kkimdev** [GameTechDev/ASSAO#6]
Especially, I wonder how ASSAO compares to http://iryoku.com/downloads/Practical-Realtime-Strategies-for-Accurate-Indirect-Occlusion.pdf .

**Comment by fstrugar** [comment]
Hi kkimdev.

GTAO seems to be a state of the art in screen space techniques nowadays and significantly advances the horizon-based approach from http://www.nvidia.com/object/siggraph-2008-HBAO.html (on which ASSAO is based), so it should provide a lot better results.
With regards to performance, the paper states that it is memory bound on GCN and, with the limitation of aiming at 60Hz, it computes the term in half-resolution and also uses temporal accumulation with reprojection. This is  different from ASSAO which computes the AO term in full resolution (except on Lowest, where it uses half resolution in checkerboard pattern) but avoids/reduces memory bandwidth (texture cache coherence) issue by doing 2x2 deinterleaved and (optional) depth MIPs. GTAO is also optimized for one target (GCN at 60Hz), so I don't know how well it scales up or down or to other HW - it'd be great to have an implementation to compare. But nevertheless, I think there's plenty of elements of the GTAO's AO term (like the thickness heuristics) that could be ported to ASSAO in the future.

Please let me know if you find an opensource GTAO implementation or even better plug it into the ExternalSSAOWrapper.h/.cpp files (which I've added for an easy comparison with any other similar AO-s), and I'll add it to the sample!

**Comment by kkimdev** [comment]
Thanks that was a very informative comment!  Yeah I couldn't find any GTAO implementation either yet :(.

**Comment by huawei-ahcox** [comment]
> Especially, I wonder how ASSAO compares to http://iryoku.com/downloads/Practical-Realtime-Strategies-for-Accurate-Indirect-Occlusion.pdf .

Link is dead but the Wayback Machine has it saved: https://web.archive.org/web/20200227014125/http://iryoku.com/downloads/Practical-Realtime-Strategies-for-Accurate-Indirect-Occlusion.pdf

**Comment by fstrugar** [comment]
Please check our GTAO implementation at https://github.com/GameTechDev/XeGTAO :)
